export default [
  { id: "16-DLCF", name: "Corpers District" },
  { id: "17-DLCF", name: "Wollex" },
  { id: "18-DLCF", name: "City College" },
  { id: "0-DLCF", name: "Abundant" },
  { id: "1-DLCF", name: "Agape" },
  { id: "2-DLCF", name: "Calvary" },
  { id: "3-DLCF", name: "Dominion" },
  { id: "4-DLCF", name: "Glory" },
  { id: "5-DLCF", name: "Goodness" },
  { id: "6-DLCF", name: "Grace" },
  { id: "7-DLCF", name: "Harmony" },
  { id: "8-DLCF", name: "Holiness" },
  { id: "9-DLCF", name: "Justice" },
  { id: "10-DLCF", name: "Mercy" },
  { id: "11-DLCF", name: "Pentecost" },
  { id: "12-DLCF", name: "Purity" },
  { id: "13-DLCF", name: "Unity" },
  { id: "14-DLCF", name: "Winner" },
  { id: "19-DLCF", name: "Victory" },
  { id: "15-DLCF", name: "Others" },
];