export default [
  { id: "16-DLCF", name: "Nasarawa State University, Keffi" },
  { id: "17-DLCF", name: "Federal University Lafia" },
  { id: "18-DLCF", name: "Bingham University Karu" },
  { id: "0-DLCF", name: "Federal Polytechnic, Nasarawa" },
  { id: "1-DLCF", name: "Nasarawa State Polytechnic, Lafia" },
  { id: "2-DLCF", name: "Collge of Education, Akwanga" },
  { id: "3-DLCF", name: "City College of Education, Mararaba" },
  { id: "4-DLCF", name: "College of Agriculture, Lafia" },
  { id: "5-DLCF", name: "School of Health Technology, Keffi" },
  { id: "6-DLCF", name: "College of Health Technology, Azuba Lafia" },
  { id: "7-DLCF", name: "Corper's Fellowship, Karu" },
  { id: "71-DLCF", name: "Corper's Fellowship, Keffi" },
  { id: "72-DLCF", name: "Corper's Fellowship, Lafia" },
  { id: "73-DLCF", name: "Corper's Fellowship, Akwanga" },
  { id: "74-DLCF", name: "Corper's Fellowship, Toto" },
  { id: "8-DLCF", name: "Non-Student Members" },
  { id: "9-DLCF", name: "School of Nursing Lafia" },
  { id: "10-DLCF", name: "Hills College of Education, Akwanga" },
  { id: "11-DLCF", name: "NACABS Polytechnic, Akwanga" },
  { id: "12-DLCF", name: "School of Nursing Alushi, Akwanga" },
  { id: "13-DLCF", name: "IT Student/SIWES" },
  { id: "13-DLCF", name: "Karu C" },
  { id: "14-DLCF", name: "Others (Specify)" },
];